import{a as B}from"./assets/vendor-DDD7fsZd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const e of s)if(e.type==="childList")for(const r of e.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&o(r)}).observe(document,{childList:!0,subtree:!0});function a(s){const e={};return s.integrity&&(e.integrity=s.integrity),s.referrerPolicy&&(e.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?e.credentials="include":s.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(s){if(s.ep)return;s.ep=!0;const e=a(s);fetch(s.href,e)}})();const M="/ArtistsHub-js-08/assets/symbol-defs-DNVN9KjG.svg",u=document.getElementById("artist-modal"),$=document.getElementById("artist-modal-close"),N=document.getElementById("modal-loader");function I(){N.classList.remove("hidden")}function S(){N.classList.add("hidden")}function x(n){n.target===u&&v()}function T(n){n.key==="Escape"&&v()}function z(){u.classList.add("is-open"),document.body.style.overflow="hidden",$.addEventListener("click",v),u.addEventListener("click",x),document.addEventListener("keydown",T)}function v(){u.classList.remove("is-open"),document.body.style.overflow="",$.removeEventListener("click",v),u.removeEventListener("click",x),document.removeEventListener("keydown",T)}async function G(n){I();try{const t=await n;document.getElementById("artist-name").textContent=t.strArtist||"Unknown",document.getElementById("artist-years").textContent=t.intFormedYear?`${t.intFormedYear}–${t.intDiedYear||"present"}`:"information missing",document.getElementById("artist-sex").textContent=t.strGender||"N/A",document.getElementById("artist-members").textContent=t.intMembers||"N/A",document.getElementById("artist-country").textContent=t.strCountry||"N/A",document.getElementById("artist-bio").textContent=t.strBiographyEN||"No biography available.",document.getElementById("artist-image").src=t.strArtistThumb;const a=document.getElementById("artist-genres");if(a.innerHTML="",Array.isArray(t.genres)&&t.genres.length>0)t.genres.forEach(s=>{const e=document.createElement("span");e.className="genre-item",e.textContent=s,a.appendChild(e)});else{const s=document.createElement("span");s.className="genre-item",s.textContent="Unknown genre",a.appendChild(s)}const o=document.getElementById("albums-container");if(o.innerHTML="",Array.isArray(t.tracksList)&&t.tracksList.length>0){const s={};t.tracksList.forEach(e=>{const r=e.strAlbum||"Unknown Album";s[r]||(s[r]=[]),s[r].push(e)}),Object.entries(s).forEach(([e,r])=>{const i=document.createElement("li");i.className="album";const c=document.createElement("h2");c.className="album-title",c.textContent=e;const d=document.createElement("div");d.className="track-list-container";const m=document.createElement("div");m.className="track-header",m.innerHTML=`
      <span>Track</span>
      <span>Time</span>
      <span>Link</span>
    `;const E=document.createElement("ul");E.className="track-list",r.forEach(f=>{const _=f.strTrackName||f.strTrack||"Unknown track",w=f.intDuration;function H(F){const A=Math.floor(Number(F)/1e3),O=Math.floor(A/60),R=A%60;return`${O}:${R.toString().padStart(2,"0")}`}const P=w?H(w):"Unknown length",C=f.movie,k=document.createElement("li");k.className="track-item",k.innerHTML=`
        <span class="track-name">${_}</span>
        <span class="track-time">${P}</span>
        ${C?`<a href="${C}" class="track-link" target="_blank" rel="noopener noreferrer">
                 <svg class="youtube-link" width="24" height="25">
                   <use href="${M}#icon-youtube"></use>
                 </svg>
               </a>`:'<span class="track-link"> </span>'}
      `,E.appendChild(k)}),d.appendChild(m),d.appendChild(E),i.appendChild(c),i.appendChild(d),o.appendChild(i)})}else{const s=document.createElement("p");s.className="no-albums",s.textContent="No tracks available.",o.appendChild(s)}z()}catch(t){console.error("Error loading artist:",t)}finally{S()}}const q="https://sound-wave.b.goit.study/api";async function K(n=1,t=8){try{return(await B.get(`${q}/artists`,{params:{page:n,limit:t}})).data}catch{return iziToast.error({message:"Sorry, there is no more artists. Please try later!",position:"topRight",messageColor:"#fff",messageSize:"16px",backgroundColor:" #EF4040",timeout:3e3}),{}}}async function Y(n=1,t=25){try{return(await B.get(`${q}/feedbacks`,{params:{page:n,limit:t}})).data.data}catch(a){return console.error("API Error:",a),{}}}const V="/ArtistsHub-js-08/assets/placeholder-CaZEGydM.jpg",j=document.querySelector(".artists-list"),g=document.querySelector("#load-more-btn");let D=1;const Z=8;async function U(){g.style.display="none",I();try{const n=await K(D,Z);if(n.artists.length===0){g.style.display="none",iziToast.info({title:"Notice",message:"No more artists to load",position:"bottomRight",messageColor:"#fff",messageSize:"16px",backgroundColor:" #EF4040",timeout:3e3});return}J(n.artists,M,V),g.style.display="flex"}catch(n){console.error("Failed to load artists:",n)}finally{S()}}function J(n,t,a){const s=n.filter(e=>e._id).map(e=>{var c,d;const r=(c=e.genres)!=null&&c.length?e.genres.map(m=>`<span class="artist-card-genre">${m}</span>`).join(""):'<span class="artist-card-genre">Unknown</span>',i=(d=e.strArtistThumb)!=null&&d.trim()?e.strArtistThumb.trim():a;return`
        <li class="artist-card" data-id="${e._id}">
          <img 
            class="artist-card-img" 
            src="${i}" 
            alt="${e.strArtist||"Unknown Artist"}" 
          />
          <div class="artist-card-content">
            <div class="artist-card-genres">${r}</div>
            <h3 class="artist-card-name">${e.strArtist||"Unknown Artist"}</h3>
            <p class="artist-card-description">
              ${e.strBiographyEN||"No description available."}
            </p>

<button type="button" class="artist-card-btn" data-artist-open data-artist-id="${e._id}">
  Learn More
  <svg class="artist-card-btn-icon" width="8" height="14">
    <use href="${t}#icon-triangle-white"></use>
  </svg>
</button>

          </div>
        </li>
      `}).join("");j.insertAdjacentHTML("beforeend",s)}function Q(){j.addEventListener("click",n=>{const t=n.target.closest("[data-artist-open]");if(!t)return;const a=t.dataset.artistId;if(!a){console.warn("Artist ID is missing — modal will not open.");return}const o=fetch(`https://sound-wave.b.goit.study/api/artists/${a}`).then(s=>s.json());G(o)})}g.addEventListener("click",async()=>{D+=1,await U()});U();Q();async function W(){const n=await Y(),t=document.querySelector("#feedback-list");t.innerHTML="";const a=n.length,o=Math.floor(a/2);n.forEach(e=>{const r=document.createElement("div");r.classList.add("swiper-slide"),r.innerHTML=`
  <div class="feedback-card">
    <div class="rating" data-rating="${e.rating}">
      <div class="rating__stars">
      ${X(e.rating)}
      </div>
    </div> 
    <p class="feedback-text">${e.descr||"—"}</p>
    <h3 class="feedback-author">${e.name||"Анонім"}</h3>
  </div>`,t.appendChild(r)});const s=new Swiper(".feedback-swiper",{slidesPerView:1,spaceBetween:32,speed:500,loop:!1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!1,renderBullet:function(e,r){return e===0||e===o||e===a-1?`<span class="${r}" data-index="${e}"></span>`:""}},on:{slideChange:function(){const e=this.activeIndex;document.querySelectorAll(".swiper-pagination span").forEach(d=>d.classList.remove("swiper-pagination-bullet-active"));let i=0;e>=a-2?i=a-1:e>=o-1&&e<=o+1?i=o:i=0;const c=document.querySelector(`.swiper-pagination [data-index="${i}"]`);c&&c.classList.add("swiper-pagination-bullet-active")}},touchRatio:1,simulateTouch:!0});s.emit("slideChange"),document.querySelectorAll(".swiper-pagination [data-index]").forEach(e=>{e.addEventListener("click",()=>{const r=parseInt(e.dataset.index);s.slideTo(r)})})}function X(n){const t=Math.round(n);return Array.from({length:5},(a,o)=>`<span class="rating__star ${o<t?"active":""}">★</span>`).join("")}document.addEventListener("DOMContentLoaded",W);const h=document.getElementById("feedback-modal"),ee=document.getElementById("close-feedback-modal"),y=document.getElementById("feedback-form"),L=document.querySelectorAll("#rating span");let p=0;document.querySelector(".feedback-section").addEventListener("click",n=>{n.target.closest(".submit-feedback-open")&&(h.classList.remove("is-hidden"),document.body.style.overflow="hidden")});ee.addEventListener("click",b);h.addEventListener("click",n=>{n.target===h&&b()});document.addEventListener("keydown",n=>{n.key==="Escape"&&b()});function b(){h.classList.add("is-hidden"),document.body.style.overflow="",y.reset(),p=0,L.forEach(n=>n.classList.remove("selected"))}L.forEach(n=>{n.addEventListener("click",()=>{p=+n.dataset.value,L.forEach(t=>{t.classList.toggle("selected",+t.dataset.value<=p)})})});y.addEventListener("submit",async n=>{n.preventDefault();const t=y.elements.name.value.trim(),a=y.elements.message.value.trim();if(!t||!a||p===0){alert("Будь ласка, заповніть усі поля та оберіть рейтинг.");return}const o={name:t,descr:a,rating:p};try{console.log("Надсилається:",o),b()}catch{alert("Помилка при надсиланні. Спробуйте ще раз.")}});const l={openBtn:document.querySelector("[data-menu-open]"),closeBtn:document.querySelector("[data-menu-close]"),mobileMenu:document.querySelector("[data-menu]")};l.openBtn.addEventListener("click",()=>{l.mobileMenu.classList.remove("is-hidden"),l.mobileMenu.classList.add("is-open"),document.body.style.overflow="hidden"});l.closeBtn.addEventListener("click",()=>{l.mobileMenu.classList.remove("is-open"),l.mobileMenu.classList.add("is-hidden"),document.body.style.overflow=""});const te=document.querySelectorAll('[data-menu] a[href*="#"]');te.forEach(n=>{n.addEventListener("click",()=>{l.mobileMenu.classList.remove("is-open"),l.mobileMenu.classList.add("is-hidden"),document.body.style.overflow=""})});
//# sourceMappingURL=index.js.map
